### ISSUE TITLE
RGB 5050 Support pin order Wemos D1

### ISSUE THREAD

**Issue by iLLiac4** [SciLor/Hyperion_LED-Controller#20]
Hi. I have tested your new implementation for RGB stripes.
I am testing on wemos D1 and by default in your code  you use pins
//#define CONFIG_LED_PWM_RED D1 //Comment in for PWM
//#define CONFIG_LED_PWM_GREEN D2 //Comment in for PWM
//#define CONFIG_LED_PWM_BLUE D3 //Comment in for PWM

Since pin D3 and D4 on the mini correspond to GPIO0 and GPIO2 on the ESP chip itself. These pins control which state the ESP chip enters at power on or reset. If GPIO0 is connected to ground, on reset, the ESP does not run your code, but waits to be programmed via its serial pins. Since using tapped controller this always happens. and I assume users will have those problems with not booting.
According to schema https://esp8266.ru/forum/attachments/d1-mini-esp8266-pinout-jpg.1541/ there are other pins capable PWM output. It would be better option for Wemos to use pins D5, D6, D7.

**Comment by SciLor** [comment]
The ConfigStatic.h needs to be changed, according to the board you use. I am using the Nodemcu-devkit-v1.0 an there the Dx PINs are mapped to other GPIOs and it works fine. Since the I am only providing one example Config It will stay that way. But I should add a bit more documentation about that.
