### ISSUE TITLE
Arilux_AL-LC0X

### ISSUE THREAD

**Issue by iLLiac4** [SciLor/Hyperion_LED-Controller#23]
Is it possible to add support for this device and keep the original function of it?
The original function is:
https://github.com/mertenats/Arilux_AL-LC03
More info about hardware:
https://www.muzik.ca/2016/11/30/hacked-esp8266-rgb-led-controller/

**Comment by SciLor** [comment]
What do you exactly need from that device?
Using the LEDs may be possible with the right configuration.

**Comment by iLLiac4** [comment]
It is device with already integrated voltage regulator so it is easy to use. The original functionality is like any other rgb led controller but with wireless. I was thinking if it is possible to use both functions at the same time; keep the original function and also have an option for hyperion from your git.

**Comment by SciLor** [comment]
Sorry I cannot easy copy one to another. If you miss any features that my code doesn't have I can implement it.
