### ISSUE TITLE
[Question] ESP32 compatible?

### ISSUE THREAD

**Issue by qwasy** [SciLor/Hyperion_LED-Controller#24]
Hi
Is it possible to make the software compatible with ESP32? They are more powerful and cost mostly the same^^
I tried compiling it myself, but it got an error in EnhancedThread...

**Comment by SciLor** [comment]
It may work. If you have an error in Enhaced Thread you may missing some libaries. without full error logs I cannot help

**Comment by qwasy** [comment]
So here's the error log, one normal and one with more infos.
[esp32_log.txt](https://github.com/SciLor/ESP8266_Hyperion_LED-Controller/files/1594439/esp32_log.txt)
[esp32_extended_log.txt](https://github.com/SciLor/ESP8266_Hyperion_LED-Controller/files/1594440/esp32_extended_log.txt)



What I mostly did, was changing the ESP8266 parts to ESP32, like the Wifi and such. And for the ESP8266 does it compile correctly.

**Comment by SciLor** [comment]
Looks like your a missing a lib.

Thread cannot be found

**Comment by mabushey** [comment]
Just want to comment I would like to do the same, this thread is very informative, thank you. :)

**Comment by qwasy** [comment]
weird...
I have the same ArduinoThread installed as in your requirements...

**Comment by SciLor** [comment]
Please check that you have got the Thread class available in your build enviroment. It looks like its missing.

**Comment by qwasy** [comment]
Oh wow. 
It does compile now^^
I changed all #include <Thread.h> to #include "Thread.h"
and put the files in the folder, and now it works. Dunno why.. the Thread.h is the same as in the library...
Weird...
Okay, so I'll just need to wait for my ESP32 to be delivered^^

**Comment by rudelm** [comment]
@qwasy can you create a PR or point to your Repo for the ESP32 version? would be really cool if this lib supports both types.

**Comment by qwasy** [comment]
edit: obsolete comment

**Comment by SciLor** [comment]
What about doing a clone of my rep and sending me a push about your changes? This way I can integrate it.

**Comment by qwasy** [comment]
never done that before^^' but I'll try

**Comment by SciLor** [comment]
You need to clone my repository, clone it to your desktop and overwrite all files with yours and commit it and push it back to your own repo. Then you can Push them over to my repo

**Comment by qwasy** [comment]
okay, I think I got it working now^^
thanks^^

**Comment by seuffert** [comment]
nice - with the changes introduced by qwasy i can confirm it is working on an esp32 :) (100 LEDs WS2801) and controlling it over UDP

**Comment by qwasy** [comment]
Awesome^^
My ESPs did arrive as well, and it works with APA102^^
edit: Nevermind, webserver works when I connect directly on the ESP^^

**Comment by SciLor** [comment]
great. Thank you for push. I will integrate it when I have found a way to use the thread library without coping it.

**Comment by SciLor** [comment]
I have ordered 2 Wemos LOLIN32 to test with.

**Comment by SciLor** [comment]
Compatible with esp32 with v0.9.0
See https://github.com/SciLor/ESP8266_Hyperion_LED-Controller/releases/tag/0.9.0
