### ISSUE TITLE
Point to correct URL in repo readme.md

### ISSUE THREAD

**Issue by rudelm** [SciLor/Hyperion_LED-Controller#25]
Hi, 

can you please update the link to the tutorial mentioned in the readme.md? http://www.forum-raspberrypi.de/Thread-hyperion-tutorial-esp8266-nodemcu-addon-wifi-led-controller-udp is redirected to https://forum-raspberrypi.de/forum/

**Comment by SciLor** [comment]
https://forum-raspberrypi.de/forum/thread/25242-tutorial-esp8266-nodemcu-addon-wifi-led-controller-udp/

I will fix that

**Comment by SciLor** [comment]
Fixed

**Comment by rudelm** [comment]
Thanks for the fast response, have a good new year!
