### ISSUE TITLE
HyperionRGB.ino:2:20: fatal error: Thread.h: No such file or directory

### ISSUE THREAD

**Issue by mabushey** [SciLor/Hyperion_LED-Controller#3]
This project looks great, but where do I get the Thread library from? I grabbed https://github.com/willemwouters/ESP8266/tree/master/projects/apps/rtos_examples/rtos_cpp/src/Thread and threw in in the HyperionRGB directory but it either doesn't work or it doesn't find it there. Sorry, I'm pretty clueless on compiling esp8266 code.

**Comment by SciLor** [comment]
You need following libraries (Search via Arduino IDE):

a) ArduinoThread
b) ArduinoJson
c) LinkedList
d) FastLED https://github.com/FastLED/FastLED
e) Logging https://github.com/SciLor/Arduino-logging-library
