### ISSUE TITLE
wifi AP

### ISSUE THREAD

**Issue by pete111** [SciLor/Hyperion_LED-Controller#41]
Hello, 
please what happens when I leave blank wifi fields?
#define CONFIG_WIFI_SSID ""
#define CONFIG_WIFI_PASSWORD ""

How can I then access webinterface? Will it behave as standalone wifi AP then?
Because I did not find access point code in sources. Many thanks and sorry if my question is wrong.

**Comment by SciLor** [comment]
Then nothing happens. There is no standalone WiFi AP function implemented.

**Comment by pete111** [comment]
it would be nice to have standalone AP if no ssid and pass is saved in SPIFFS. And maybe to have an option to change AP ssid and pass also, so just simple storing of these values in SPIFFS as well :) It would be coool.

**Comment by SciLor** [comment]
Implemented via https://github.com/SciLor/Hyperion_LED-Controller/commit/949a57b61cf51f69bfc742efbb7937734de7f58f
