### ISSUE TITLE
ESP freezes....

### ISSUE THREAD

**Issue by crazy888** [SciLor/Hyperion_LED-Controller#46]
Hi,

i´m running LED Controller on a ESP8266.

It works until i start some special colors.
I.e. it freeze when using effect "cinema brighten lights".
I have to restart the ESP. Then it is working again. It freeze everytime i do this effect.

I´m using 5m Stripe of WS2812B LEDs. I have 300 LEDs running.

**Comment by SciLor** [comment]
Please Set the Log on verbose and post the log here. Please check if it happens with other colors or effects. Please try to reproduce the problem without hyperion, only with the esp and the hyperion app. 


But I don't think it's an issue with my software, as I am also using 300 LEDs, but with LPD8806. Maybe you got a power supply problem?

**Comment by crazy888** [comment]
so i have done some testing:

logfile here : [https://pastebin.com/za6uLfXK](https://pastebin.com/za6uLfXK)

What i have done:
- I have shutdown my remote instanz of hyperion on my pi
- I controlled the ESP with my Hyperion Android app
- I set loglevel to verbose
- I toggle between the 2 effects which are listed and set some colours with the colour weel
- I have changed the power supply (currently using: 5V DC with 18A)

What happens:
- The ESP stucks randomly during chosing effects and fix colours.
- The ESP stays activ and the comport log still outputs log lines
- It feels like the ESP got a 100% cpu load problem
- During these stuck effects it sometime set colours which have been selected 15 seconds before
- Reconnecting with the hyperion android app also works sometime with delays

I realy have no clue whats wrong with my setup......

**Comment by SciLor** [comment]
The slowdowns are normal when you have logging on. Also when it is controlled from hyperion.
Check your GND lines, the power supply should be enough. But you need to power (if you use it as ambilight) on all 4-edges.
You may also try to power your ESP with the same power supply as the LEDs or the other way round.

**Comment by crazy888** [comment]
Done more testing:

I flashed a vanilla FastLed example (Cyclone) on the ESP.
It works flawless without any problem.

I have only 1 power supply for both and only 1 Power input at the left side.
The 5 meters are in one line hanging on my roof. No Ambilight mode.

**Comment by SciLor** [comment]
You should really power it from 4 points. Otherwise it really looses brightness.
I have no idea. Try to disable logging. This should increase the performance. And you may decrease the baudrate of hyperion.

**Comment by crazy888** [comment]
Flashed back the sketch and added static color at start mode.
It is not able to load the color and crash at startup. (see photo) 
Left side is white and at the end it stays red?

Maybe i should power the esp with additionaly power supply. Will try this tomorrow.

![img_20180912_212033](https://user-images.githubusercontent.com/16318281/45448157-f46cef00-b6d1-11e8-8c23-181518d498d2.jpg)

**Comment by SciLor** [comment]
If you got a crash, please post the error log output of the esp, because it prints out a reason/stack via serial.

PS: Looks great!

**Comment by crazy888** [comment]
`I:  CFG=Static config loaded
D:   Chipset=Clockless, dataPin=5, clockPin=NONE, colorOrder=66, ledCount=300
I:  Reset Mode
I:  Mode changed to 2
D:   WrapperWiFi(ssid="Oliver", password="*aaaaaa*")
I:  Connecting to WiFi Oliver
I:  Using static ip
I:  Connected successfully, IP address: 192.168.1.15
I:  Prepare OTA
D:   WrapperOTA(hostname="ESP8266Hyperion")
I:  OTA Ready
I:  Open port 19446 for UDP...
I:  success
I:  Open port 19444 for TCP...
I:  HEAP=39984
D:   HEAP=40104
D:   HEAP=39600
D:   HEAP=39456
D:   HEAP=39184
D:   HEAP=39456
D:   HEAP=39496
D:   HEAP=39328
D:   HEAP=39288
D:   HEAP=39288
D:   HEAP=39288
D:   HEAP=39288
D:   HEAP=39160
D:   HEAP=39152
D:   HEAP=39288
D:   HEAP=39288
`
ESP seems to be alive. It´s plotting these HEAP things all the time. Just the LEDs seems to be frozen!

**Comment by SciLor** [comment]
The Heap mean everything is fine. It is a heartbeat.
The LEDs you using are 3 wired? You should check the web for known problems with those ones and possible solutions

**Comment by crazy888** [comment]
Yes ist 3-Wire without clock (maybe the wrong decision).... WS2812b

I tried to drive it with my raspi and hyperion over the SPI interface.
It is facing the same problem. Flickering and freezes .......
I think maybe is my LED stripe damaged....? 
I ordered already a new one but china delivery takes about 3 week :(

**Comment by SciLor** [comment]
I will close this ticket, because the problem is not related to code but to hardware.
Feel free to post here, if you have got your new LED-Strip
