### ISSUE TITLE
Compilation error on arduinoIDE

### ISSUE THREAD

**Issue by ellisium** [SciLor/Hyperion_LED-Controller#48]
Hello,

Not sure if an issue or wrong configuration but I can't compile on a nodemcu lolin v3
Thank you

arduino IDE logs:
`Les options de compilation ont été modifiées, tout sera recompilé
ATTENTION : la bibliothèque Esplora prétend être exécutable sur la (ou les) architecture(s) (avr) et peut être incompatible avec votre carte actuelle qui s'exécute sur (esp8266).
In file included from sketch\WrapperLedControl.h:6:0,

                 from C:\Users\elelay\Downloads\ESP8266_Hyperion_LED-Controller-0.8.4\ESP8266_Hyperion_LED-Controller-0.8.4\HyperionRGB\HyperionRGB.ino:14:

C:\Users\elelay\Documents\Arduino\libraries\FastLED/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.003

 #    pragma message "FastLED version 3.001.003"

                     ^

In file included from C:\Users\elelay\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

                 from sketch\WrapperLedControl.h:6,

                 from C:\Users\elelay\Downloads\ESP8266_Hyperion_LED-Controller-0.8.4\ESP8266_Hyperion_LED-Controller-0.8.4\HyperionRGB\HyperionRGB.ino:14:

C:\Users\elelay\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

In file included from sketch\WrapperLedControl.h:6:0,

                 from sketch\WrapperLedControl.cpp:1:

C:\Users\elelay\Documents\Arduino\libraries\FastLED/FastLED.h:17:21: note: #pragma message: FastLED version 3.001.003

 #    pragma message "FastLED version 3.001.003"

                     ^

In file included from C:\Users\elelay\Documents\Arduino\libraries\FastLED/FastLED.h:65:0,

                 from sketch\WrapperLedControl.h:6,

                 from sketch\WrapperLedControl.cpp:1:

C:\Users\elelay\Documents\Arduino\libraries\FastLED/fastspi.h:110:23: note: #pragma message: No hardware SPI pins defined.  All SPI access will default to bitbanged output

 #      pragma message "No hardware SPI pins defined.  All SPI access will default to bitbanged output"

                       ^

C:\Program Files (x86)\Arduino\libraries\Esplora\src\Esplora.cpp:35:36: error: 'A1' was not declared in this scope

 const byte MUX_ADDR_PINS[] = { A0, A1, A2, A3 };

                                    ^

C:\Program Files (x86)\Arduino\libraries\Esplora\src\Esplora.cpp:35:40: error: 'A2' was not declared in this scope

 const byte MUX_ADDR_PINS[] = { A0, A1, A2, A3 };

                                        ^

C:\Program Files (x86)\Arduino\libraries\Esplora\src\Esplora.cpp:35:44: error: 'A3' was not declared in this scope

 const byte MUX_ADDR_PINS[] = { A0, A1, A2, A3 };

                                            ^

C:\Program Files (x86)\Arduino\libraries\Esplora\src\Esplora.cpp:36:26: error: 'A4' was not declared in this scope

 const byte MUX_COM_PIN = A4;

                          ^

C:\Program Files (x86)\Arduino\libraries\Esplora\src\Esplora.cpp:53:26: error: 'A5' was not declared in this scope

 const byte ACCEL_X_PIN = A5;

                          ^

C:\Program Files (x86)\Arduino\libraries\Esplora\src\Esplora.cpp:54:26: error: 'A11' was not declared in this scope

 const byte ACCEL_Y_PIN = A11;

                          ^

C:\Program Files (x86)\Arduino\libraries\Esplora\src\Esplora.cpp:55:26: error: 'A6' was not declared in this scope

 const byte ACCEL_Z_PIN = A6;

                          ^

exit status 1
Erreur de compilation pour la carte NodeMCU 1.0 (ESP-12E Module)`

**Comment by SciLor** [comment]
You have included a lib called "Esplora" which makes problems.
Please also check if you are using the recommended versions of the needed libs in my readme.

**Comment by ellisium** [comment]
Sorry, I confirm I used not the right project. not a defect.
@SciLor STATIC_COLOR is a configurable variable? or will be just white color?
In addition, using nodemcu + ws8212b, when I turn on it, the first led is white or green up to the HYPERION_UDP connect. (working as expected after conenction) Any hardware workaround about it?

And BIG THX for this awesome repo

**Comment by SciLor** [comment]
Please try the dev branch. 
In the ConfigStatic.h you will have a 
`#define CONFIG_LED_STATIC_COLOR CRGB(254, 254, 254)`
Set it to CRGB(0,0,0) for Black and set
`#define CONFIG_LED_STANDARD_MODE STATIC_COLOR`
