### ISSUE TITLE
For CONFIG_LED_STANDARD_MODE=OFF LEDs may not be initialized upon power on

### ISSUE THREAD

**Issue by ytmytm** [SciLor/Hyperion_LED-Controller#54]
If `CONFIG_LED_STANDARD_MODE` is defined to be `OFF` then upon power-on the leds may remain in random state, not initialized to be really off.

This is because `changeMode()` compares `newMode` with `activeMode` and the latter one is not set to a neutral value on sketch reset, so that changeMode() actions would fire every time on startup.

To fix this simply add a new mode to `Mode` enum in BaseHeader.h:
```
enum Mode { NONE, OFF, HYPERION_UDP, STATIC_COLOR, RAINBOW, FIRE2012 };
```
and initialize `activeMode` in HyperionRGB.ino:
```
Mode activeMode = NONE;
```

**Comment by SciLor** [comment]
https://github.com/SciLor/Hyperion_LED-Controller/commit/8d2733a439fe7b48b7134d073af9db1872ce5a39
