### ISSUE TITLE
Missing ; in HyperionRGB.ino on line 204

### ISSUE THREAD

**Issue by BKayCode** [SciLor/Hyperion_LED-Controller#65]
As the title says:
missing ; in HyperionRGB.ino on line 204.

While compiling the following error occurs:
"exit status 1
expected ';' before 'Log'"

**Comment by SciLor** [comment]
Thank you, you may add the missing semicolon or enable the Webconfig within the ConfigStatic.h

`#define CONFIG_ENABLE_WEBCONFIG 1`

**Comment by SciLor** [comment]
https://github.com/SciLor/Hyperion_LED-Controller/commit/5bbc107e87dde20027a0d9406e80cd2f33cce27f
